In [3]:
dic = {1:1, 2:4,3:6,4:9}

In [4]:
dic[2]

4

In [5]:
dic[4]

9

In [8]:
dic[5] = 20 #새로운 요소 추가

In [9]:
print(dic)

{1: 1, 2: 4, 3: 6, 4: 9, 5: 20}


In [10]:
dic.keys()

dict_keys([1, 2, 3, 4, 5])

In [11]:
dic.values()

dict_values([1, 4, 6, 9, 20])

In [12]:
dic.items()

dict_items([(1, 1), (2, 4), (3, 6), (4, 9), (5, 20)])

In [13]:
for key, val in dic.items():
    print(key,val)

1 1
2 4
3 6
4 9
5 20


In [14]:
for key in dic.keys():
    dic[key] = dic[key]*0.5

In [15]:
print(dic)

{1: 0.5, 2: 2.0, 3: 3.0, 4: 4.5, 5: 10.0}


In [17]:
L = [1,2,3,4,5]
for l in L:
    print(l)
    if l == 3:
        break

1
2
3


In [18]:
list(range(1,5,2))

[1, 3]

In [20]:
for i in range(2,10):
    for j in range(2,10):
        print('{}*{}={}'.format(i,j,i*j))

2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81


In [21]:
import itertools

In [22]:
for a,b,c in itertools.product(range(5),range(5),range(5)):
    print(a,b,c)

0 0 0
0 0 1
0 0 2
0 0 3
0 0 4
0 1 0
0 1 1
0 1 2
0 1 3
0 1 4
0 2 0
0 2 1
0 2 2
0 2 3
0 2 4
0 3 0
0 3 1
0 3 2
0 3 3
0 3 4
0 4 0
0 4 1
0 4 2
0 4 3
0 4 4
1 0 0
1 0 1
1 0 2
1 0 3
1 0 4
1 1 0
1 1 1
1 1 2
1 1 3
1 1 4
1 2 0
1 2 1
1 2 2
1 2 3
1 2 4
1 3 0
1 3 1
1 3 2
1 3 3
1 3 4
1 4 0
1 4 1
1 4 2
1 4 3
1 4 4
2 0 0
2 0 1
2 0 2
2 0 3
2 0 4
2 1 0
2 1 1
2 1 2
2 1 3
2 1 4
2 2 0
2 2 1
2 2 2
2 2 3
2 2 4
2 3 0
2 3 1
2 3 2
2 3 3
2 3 4
2 4 0
2 4 1
2 4 2
2 4 3
2 4 4
3 0 0
3 0 1
3 0 2
3 0 3
3 0 4
3 1 0
3 1 1
3 1 2
3 1 3
3 1 4
3 2 0
3 2 1
3 2 2
3 2 3
3 2 4
3 3 0
3 3 1
3 3 2
3 3 3
3 3 4
3 4 0
3 4 1
3 4 2
3 4 3
3 4 4
4 0 0
4 0 1
4 0 2
4 0 3
4 0 4
4 1 0
4 1 1
4 1 2
4 1 3
4 1 4
4 2 0
4 2 1
4 2 2
4 2 3
4 2 4
4 3 0
4 3 1
4 3 2
4 3 3
4 3 4
4 4 0
4 4 1
4 4 2
4 4 3
4 4 4


In [25]:
for a,b in itertools.product(range(2,10),range(2,10)):
    print('{}*{}={}'.format(a,b,a*b))


2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81


In [26]:
# zip
for a,b,c in zip(range(5),range(5),range(5)):
    print(a,b,c)

0 0 0
1 1 1
2 2 2
3 3 3
4 4 4


In [30]:
L =['a','b','c','d']
for comb in itertools.combinations(L,3):
    print(comb)

('a', 'b', 'c')
('a', 'b', 'd')
('a', 'c', 'd')
('b', 'c', 'd')


In [32]:
for r in range(1,len(L)+1):
    for p in itertools.permutations(L,r):
        print(p)

('a',)
('b',)
('c',)
('d',)
('a', 'b')
('a', 'c')
('a', 'd')
('b', 'a')
('b', 'c')
('b', 'd')
('c', 'a')
('c', 'b')
('c', 'd')
('d', 'a')
('d', 'b')
('d', 'c')
('a', 'b', 'c')
('a', 'b', 'd')
('a', 'c', 'b')
('a', 'c', 'd')
('a', 'd', 'b')
('a', 'd', 'c')
('b', 'a', 'c')
('b', 'a', 'd')
('b', 'c', 'a')
('b', 'c', 'd')
('b', 'd', 'a')
('b', 'd', 'c')
('c', 'a', 'b')
('c', 'a', 'd')
('c', 'b', 'a')
('c', 'b', 'd')
('c', 'd', 'a')
('c', 'd', 'b')
('d', 'a', 'b')
('d', 'a', 'c')
('d', 'b', 'a')
('d', 'b', 'c')
('d', 'c', 'a')
('d', 'c', 'b')
('a', 'b', 'c', 'd')
('a', 'b', 'd', 'c')
('a', 'c', 'b', 'd')
('a', 'c', 'd', 'b')
('a', 'd', 'b', 'c')
('a', 'd', 'c', 'b')
('b', 'a', 'c', 'd')
('b', 'a', 'd', 'c')
('b', 'c', 'a', 'd')
('b', 'c', 'd', 'a')
('b', 'd', 'a', 'c')
('b', 'd', 'c', 'a')
('c', 'a', 'b', 'd')
('c', 'a', 'd', 'b')
('c', 'b', 'a', 'd')
('c', 'b', 'd', 'a')
('c', 'd', 'a', 'b')
('c', 'd', 'b', 'a')
('d', 'a', 'b', 'c')
('d', 'a', 'c', 'b')
('d', 'b', 'a', 'c')
('d', 'b', 'c',

In [33]:
import numpy as np

In [35]:
a = np.array([1,4,2,5,3])
b = np.array([3.14, 4, 2, 3])
c = np.array([1,2,3,4,],dtype= float)
print(a,b,c)

[1 4 2 5 3] [3.14 4.   2.   3.  ] [1. 2. 3. 4.]


In [36]:
a = np.zeros((3,5), dtype = int)

In [37]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
b = np.ones((3,5), dtype = float)

In [39]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
c = np.full((3,5), 3.14) # 3.14로 채운 배열 만들기
c

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [41]:
d = np.arange(0,22,2) # 0에서 시작해 2씩 더해 20까지 채우는 배열 생성

In [43]:
d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
e = np.linspace(0,1,5) # 0,1사이의 일정한 간격으로 값 생성
e

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.random.random((3,5))

array([[0.8300319 , 0.40367706, 0.24310901, 0.21254564, 0.50334342],
       [0.63873444, 0.78010122, 0.58711474, 0.17044239, 0.46672172],
       [0.24004053, 0.01521652, 0.18376206, 0.73445246, 0.46671136]])

In [46]:
np.arange(3)

array([0, 1, 2])

In [47]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])

In [2]:
import pandas as pd

In [3]:
S = pd.Series({'a':1, 'b':2,'c':3})

In [4]:
S = pd.Series([1,2,3,4], index = ['a','b','c','d'])

In [5]:
S

a    1
b    2
c    3
d    4
dtype: int64

In [6]:
S.values

array([1, 2, 3, 4], dtype=int64)

In [7]:
S.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[1,2,3,4]}, index = [1,2,3,4])

In [9]:
df

col1  col2
1     1     1
2     2     2
3     3     3
4     4     4

In [10]:
df.values

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]], dtype=int64)

In [12]:
type(df.values)

numpy.ndarray

In [13]:
S = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
S

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
S.loc['a']

1

In [15]:
S.iloc[1]

2

In [16]:
S.loc['a':'c']

a    1
b    2
c    3
dtype: int64

In [17]:
S.iloc[1:3]

b    2
c    3
dtype: int64

In [18]:
df[['col1','col2']]

col1  col2
1     1     1
2     2     2
3     3     3
4     4     4

In [22]:
df = pd.DataFrame({"col1": [1, 2, 3, 4],
                  "col2": [5, 6, 7, 8]}, 
                  index = ['a', 'b', 'c', 'd'])

In [23]:
df['col1']

a    1
b    2
c    3
d    4
Name: col1, dtype: int64

In [24]:
df[['col1']]

col1
a     1
b     2
c     3
d     4

In [25]:
df.loc['a','col1']

1

In [26]:
df.loc['a':'c','col1']

a    1
b    2
c    3
Name: col1, dtype: int64

In [28]:
df

col1  col2
a     1     5
b     2     6
c     3     7
d     4     8

In [30]:
df.iloc[1:3,0:1]

col1
b     2
c     3

In [31]:
# 모든 행과 모든 열을 보여주기
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [39]:
import numpy as np
df = pd.DataFrame(np.random.random(size = (500,5)),columns = ['X1','X2,','X3','X4','X5'])
df

X1       X2,        X3        X4        X5
0    0.025096  0.449968  0.161461  0.798028  0.793400
1    0.007147  0.536233  0.433969  0.994107  0.289270
2    0.386752  0.278117  0.693538  0.654298  0.202071
3    0.299077  0.599146  0.168441  0.783881  0.742958
4    0.777876  0.437573  0.940975  0.753361  0.881432
5    0.777146  0.559670  0.420487  0.578098  0.618683
6    0.958340  0.459385  0.526001  0.488263  0.209334
7    0.918941  0.988000  0.032969  0.677039  0.656705
8    0.370803  0.684076  0.005203  0.562167  0.172684
9    0.523859  0.756514  0.357072  0.823168  0.396155
10   0.146207  0.770727  0.232532  0.395887  0.462373
11   0.800602  0.162969  0.808733  0.416378  0.305431
12   0.539694  0.549429  0.748022  0.982799  0.181904
13   0.949523  0.973807  0.147669  0.323153  0.361769
14   0.530984  0.607516  0.614221  0.878942  0.948380
15   0.924650  0.595132  0.864545  0.847361  0.415752
16   0.906183  0.525233  0.419556  0.908715  0.820746
17   0.574725  0.650915  0.743481  0.586662  0.860422
18   0.048025  0.387852  0.273483  0.118754  0.696565
19   0.996760  0.948465  0.756895  0.864748  0.228558
20   0.807036  0.420011  0.904081  0.446769  0.092289
21   0.174136  0.848242  0.921826  0.278730  0.886568
22   0.254984  0.859191  0.747354  0.212298  0.062603
23   0.963171  0.401166  0.503445  0.867997  0.212760
24   0.424678  0.509852  0.029406  0.947370  0.453409
25   0.801775  0.497451  0.262455  0.910947  0.969056
26   0.813227  0.480027  0.185058  0.654371  0.523196
27   0.723347  0.081932  0.961133  0.088988  0.248156
28   0.192862  0.066287  0.258933  0.598781  0.122940
29   0.776564  0.430050  0.564778  0.654714  0.321059
30   0.966390  0.538798  0.761220  0.652707  0.564541
31   0.719739  0.844250  0.843002  0.323924  0.639909
32   0.144861  0.128770  0.178290  0.255059  0.326750
33   0.808722  0.750671  0.272787  0.238755  0.142677
34   0.299178  0.497998  0.274693  0.671097  0.910065
35   0.007070  0.883888  0.755175  0.580826  0.890572
36   0.348391  0.692056  0.268749  0.566001  0.540975
37   0.733500  0.897748  0.326224  0.998488  0.617078
38   0.395712  0.934345  0.346418  0.978727  0.454534
39   0.367473  0.740228  0.318665  0.691211  0.326987
40   0.845350  0.925888  0.513852  0.767449  0.866165
41   0.505001  0.391343  0.852349  0.589549  0.790704
42   0.154231  0.127986  0.329345  0.203005  0.116609
43   0.637970  0.683003  0.433976  0.544190  0.235000
44   0.167782  0.490503  0.996783  0.150284  0.512670
45   0.962663  0.966256  0.296888  0.791724  0.905910
46   0.672555  0.160922  0.691460  0.600278  0.650619
47   0.874601  0.912237  0.334314  0.779534  0.345692
48   0.369394  0.677455  0.275684  0.580116  0.520727
49   0.423974  0.034655  0.433293  0.465561  0.111775
50   0.733144  0.056312  0.765058  0.133186  0.264483
51   0.984738  0.573359  0.701133  0.026487  0.484644
52   0.959159  0.237425  0.795881  0.987422  0.920812
53   0.947238  0.138022  0.050931  0.719831  0.452997
54   0.788027  0.106099  0.298219  0.223351  0.441871
55   0.757193  0.035017  0.620254  0.890789  0.158916
56   0.963475  0.932719  0.450405  0.023025  0.572206
57   0.990077  0.582279  0.950908  0.587461  0.782331
58   0.829759  0.182143  0.653806  0.865233  0.490097
59   0.919448  0.975775  0.924041  0.423677  0.318453
60   0.712454  0.082457  0.315099  0.915990  0.579912
61   0.420348  0.974717  0.113853  0.393656  0.172203
62   0.304461  0.361017  0.713819  0.775225  0.061220
63   0.530015  0.633205  0.858206  0.164826  0.830239
64   0.373894  0.812679  0.188028  0.176114  0.662442
65   0.579647  0.711410  0.217694  0.630669  0.379001
66   0.886677  0.694675  0.779289  0.984693  0.734031
67   0.739387  0.053255  0.786702  0.563050  0.683888
68   0.148736  0.502922  0.670461  0.323753  0.525578
69   0.857886  0.083524  0.751354  0.756351  0.872482
70   0.382976  0.250654  0.836622  0.559945  0.953633
71   0.662379  0.779069  0.767291  0.326406  0.093044
72   0.055756  0.055672  0.299649  0.749464  0.982902
73   0.501685  

In [40]:
df.head()

X1       X2,        X3        X4        X5
0  0.025096  0.449968  0.161461  0.798028  0.793400
1  0.007147  0.536233  0.433969  0.994107  0.289270
2  0.386752  0.278117  0.693538  0.654298  0.202071
3  0.299077  0.599146  0.168441  0.783881  0.742958
4  0.777876  0.437573  0.940975  0.753361  0.881432

In [41]:
df.columns

Index(['X1', 'X2,', 'X3', 'X4', 'X5'], dtype='object')

In [43]:
df.dtypes

X1     float64
X2,    float64
X3     float64
X4     float64
X5     float64
dtype: object

In [44]:
df.iloc[1,2]

0.4339694988943289

In [45]:
df.iloc[1,1] = 'change'

In [46]:
df.head()

X1       X2,        X3        X4        X5
0  0.025096  0.449968  0.161461  0.798028  0.793400
1  0.007147    change  0.433969  0.994107  0.289270
2  0.386752  0.278117  0.693538  0.654298  0.202071
3  0.299077  0.599146  0.168441  0.783881  0.742958
4  0.777876  0.437573  0.940975  0.753361  0.881432

In [47]:
import os

In [48]:
os.getcwd()

'C:\\Users\\신상훈\\Documents\\GitHub\\preprocessing\\practice'

In [49]:
import os
os.chdir(r'C:\Users\신상훈\Desktop\preprocessing\part-1.-데이터-핸들링\1. 데이터 핸들링\데이터')

In [56]:
f = open('data_reading.csv','r')
data = f.read()
data[1:1000]

'ol1,Col2,Col3,Col4,Col5\n0.18888809146420238,0.16105292892696288,0.1504127702525998,0.8247702147554103,0.11183287230275862\n0.8277194258724868,0.16136254345104883,0.400331159000502,0.3981961133865768,0.7706960076672201\n0.844660181886513,0.10099782620549302,0.995176205519609,0.6155252896856449,0.8783894199796791\n0.9138952685419564,0.036168779255092876,0.2378403402407797,0.18762834416630736,0.5343081969025114\n0.32244342400394976,0.9550099806308116,0.3407646382285975,0.6493109172840262,0.35453974816238576\n0.3306251110157733,0.6720388851049659,0.10938064887311616,0.07568233209352304,0.9169313724492655\n0.24768623373487852,0.6864049104199853,0.7279423564551321,0.07051655013435276,0.5932367728578449\n0.5457259900662517,0.8259997208239563,0.222939569582428,0.5272524587280554,0.9494463062496303\n0.45737316471560596,0.6199415331357327,0.9979776426734485,0.3682306861093537,0.41162690950241676\n0.8637387893511083,0.685755037957085,0.7069687998728162,0.7456995967962297,0.2888004054518888\n0.6

In [57]:
def make_float(x):
    try:
        return float
    except:
        return x
    
data = [[make_float(value) for value in line.split(',')] for line in data.split('\n')]
data

[[float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, float, float, float, float],
 [float, flo

In [59]:
f = open('data_reading.csv','r')
header = f.readline() # 첫 번째 row를 읽어옴
data = []

line = f.readline() # 두 번째 row를 읽음
while line: # line이 빈 문자열이 될 때 까지
    data.append(list(map(float, line.split(','))))
    line = f.readline()
f.close()

In [60]:
header

'Col1,Col2,Col3,Col4,Col5\n'

In [61]:
data

[[0.18888809146420238,
  0.16105292892696288,
  0.1504127702525998,
  0.8247702147554103,
  0.11183287230275862],
 [0.8277194258724868,
  0.16136254345104883,
  0.400331159000502,
  0.3981961133865768,
  0.7706960076672201],
 [0.844660181886513,
  0.10099782620549302,
  0.995176205519609,
  0.6155252896856449,
  0.8783894199796791],
 [0.9138952685419564,
  0.036168779255092876,
  0.2378403402407797,
  0.18762834416630736,
  0.5343081969025114],
 [0.32244342400394976,
  0.9550099806308116,
  0.3407646382285975,
  0.6493109172840262,
  0.35453974816238576],
 [0.3306251110157733,
  0.6720388851049659,
  0.10938064887311616,
  0.07568233209352304,
  0.9169313724492655],
 [0.24768623373487852,
  0.6864049104199853,
  0.7279423564551321,
  0.07051655013435276,
  0.5932367728578449],
 [0.5457259900662517,
  0.8259997208239563,
  0.222939569582428,
  0.5272524587280554,
  0.9494463062496303],
 [0.45737316471560596,
  0.6199415331357327,
  0.9979776426734485,
  0.3682306861093537,
  0.411626909

In [62]:
line

''

#### write를 이용한 데이터 쓰기

In [63]:
','.join(list(map(str,data[2])))

'0.844660181886513,0.10099782620549302,0.995176205519609,0.6155252896856449,0.8783894199796791'

In [64]:
data[1]

[0.8277194258724868,
 0.16136254345104883,
 0.400331159000502,
 0.3981961133865768,
 0.7706960076672201]

In [65]:
data[2]

[0.844660181886513,
 0.10099782620549302,
 0.995176205519609,
 0.6155252896856449,
 0.8783894199796791]

In [2]:
import os
import pandas as pd
os.chdir(r'C:\Users\신상훈\Desktop\preprocessing\part-1.-데이터-핸들링\1. 데이터 핸들링\데이터')

In [3]:
df = pd.read_csv('data_reading.csv')
df.head()

Col1      Col2      Col3      Col4      Col5
0  0.188888  0.161053  0.150413  0.824770  0.111833
1  0.827719  0.161363  0.400331  0.398196  0.770696
2  0.844660  0.100998  0.995176  0.615525  0.878389
3  0.913895  0.036169  0.237840  0.187628  0.534308
4  0.322443  0.955010  0.340765  0.649311  0.354540

In [4]:
df = pd.read_csv('data_reading_tap.txt', sep = '\t')
df.head()

Col1      Col2      Col3      Col4      Col5
0  0.188888  0.161053  0.150413  0.824770  0.111833
1  0.827719  0.161363  0.400331  0.398196  0.770696
2  0.844660  0.100998  0.995176  0.615525  0.878389
3  0.913895  0.036169  0.237840  0.187628  0.534308
4  0.322443  0.955010  0.340765  0.649311  0.354540

In [5]:
df.columns = ['X1','X2','X3','X5','X4']
df.head()

X1        X2        X3        X5        X4
0  0.188888  0.161053  0.150413  0.824770  0.111833
1  0.827719  0.161363  0.400331  0.398196  0.770696
2  0.844660  0.100998  0.995176  0.615525  0.878389
3  0.913895  0.036169  0.237840  0.187628  0.534308
4  0.322443  0.955010  0.340765  0.649311  0.354540

In [6]:
df = pd.read_csv('large_data_with_ID.csv',usecols = [0,1,5,10],# ['ID', 'X1', 'X5', 'X10']으로 불러와도 무방
                index_col = 'ID', # usecols을 사용하는 경우, index_col을 반드시 포함시켜야 함
                nrows = 1000)
df.head()

X1  X5  X10
ID              
ID1  21   3   60
ID2   0  69   98
ID3  75  69   49
ID4  66  86   22
ID5  33  57   59

In [7]:
df.to_csv('to_csv를 이용한 데이터 저장_인덱스 미포함.csv',sep = ',', index = False)

In [9]:
df = pd.read_excel('data_reading.xlsx')
df

첫번째 시트  값없음
0  첫번째 시트  값없음

In [10]:
df = pd.read_excel('data_reading.xlsx', sheet_name = 'target_sheet')
df.head()

Col1      Col2      Col3      Col4      Col5
0  0.188888  0.161053  0.150413  0.824770  0.111833
1  0.827719  0.161363  0.400331  0.398196  0.770696
2  0.844660  0.100998  0.995176  0.615525  0.878389
3  0.913895  0.036169  0.237840  0.187628  0.534308
4  0.322443  0.955010  0.340765  0.649311  0.354540

In [11]:
df = pd.read_excel("월별매출데이터.xlsx",sheet_name = '6월', skiprows = range(6))
df.head()

Unnamed: 0        일자   지점   품명  수량 주문인 ID           수령 주소 주문 상태  결제 수단
0         NaN  2018.6.1  지점1  제품C   8  C-228  서울특별시 서대문구 홍제동  주문완료  인터넷뱅킹
1         NaN  2018.6.1  지점4  제품F   8  C-243   서울특별시 송파구 마천동  주문완료  인터넷뱅킹
2         NaN  2018.6.1  지점4  제품D   3  C-191   서울특별시 노원구 월계동   배송중   신용카드
3         NaN  2018.6.1  지점2  제품D   0  C-271  서울특별시 중구 회현동3가  배송완료  휴대폰결제
4         NaN  2018.6.1  지점4  제품D   8  C-244   서울특별시 중구 서소문동  배송완료  인터넷뱅킹

In [12]:
df = df.iloc[:,1:]
df.head()

일자   지점   품명  수량 주문인 ID           수령 주소 주문 상태  결제 수단
0  2018.6.1  지점1  제품C   8  C-228  서울특별시 서대문구 홍제동  주문완료  인터넷뱅킹
1  2018.6.1  지점4  제품F   8  C-243   서울특별시 송파구 마천동  주문완료  인터넷뱅킹
2  2018.6.1  지점4  제품D   3  C-191   서울특별시 노원구 월계동   배송중   신용카드
3  2018.6.1  지점2  제품D   0  C-271  서울특별시 중구 회현동3가  배송완료  휴대폰결제
4  2018.6.1  지점4  제품D   8  C-244   서울특별시 중구 서소문동  배송완료  인터넷뱅킹

In [1]:
import os
import pandas as pd
os.chdir(r'C:\Users\신상훈\Desktop\preprocessing\part-1.-데이터-핸들링\1. 데이터 핸들링\데이터')

In [2]:
df1 = pd.read_csv('merge_실습_employee_group.csv', engine = 'python')
df2 = pd.read_csv('merge_실습_employee_hire_date.csv', engine = 'python')

In [3]:
df1.head()

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [4]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [5]:
df2.head()

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [6]:
merge_df = pd.merge(df1,df2)

In [7]:
merge_df

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [10]:
merged_df = pd.merge(df1,df2,on = 'employee')
merged_df.head()

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [14]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [15]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [17]:
df1 = pd.read_csv("merge_실습_employee_group.csv", engine = "python")
df2 = pd.read_csv("merge_실습_name_hire_date.csv", engine = "python")

In [18]:
merged_df = pd.merge(df1, df2, left_on = "employee", right_on = "name")
merged_df.head() # employee와 name 모두 살아 있어서, 하나를 제거해줘야 함

employee        group  hire_date  name
0      Bob   Accounting       2008   Bob
1     Jake  Engineering       2012  Jake
2     Lisa  Engineering       2004  Lisa
3      Sue           HR       2014   Sue

In [19]:
merged_df.drop('name', axis = 1, inplace = True)
merged_df.head()

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [24]:
df1 = pd.read_csv("merge_실습_employee_group.csv", engine = "python")
df2 = pd.read_csv("merge_실습_name_hire_date.csv", engine = "python", index_col = "name")

In [25]:
df2.head()

hire_date
name           
Lisa       2004
Bob        2008
Jake       2012
Sue        2014

In [27]:
df1 = pd.read_csv('merge_실습_employee_group.csv', engine = 'python')
df2 = pd.read_csv('merge_실습_name_hire_date.csv',engine = 'python', index_col = 'name')

In [28]:
merged_df = pd.merge(df1,df2,left_on = 'employee', right_index = True)

In [29]:
merged_df.head()

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [31]:
import os
import pandas as pd
os.chdir(r'C:\Users\신상훈\Desktop\preprocessing\part-1.-데이터-핸들링\1. 데이터 핸들링\데이터')

In [33]:
df1 = pd.DataFrame({'A':[1,2,3,4],
                   'B':[1,2,3,4]})

In [34]:
df1

A  B
0  1  1
1  2  2
2  3  3
3  4  4

In [35]:
df2 = pd.DataFrame({'A':[5,6,7,8],
                   'B':[5,6,7,8]})

In [39]:
merged_df = pd.concat([df1, df2], axis = 0, ignore_index = True)
merged_df

A  B
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
5  6  6
6  7  7
7  8  8

In [40]:
merged_df

A  B
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
5  6  6
6  7  7
7  8  8

In [42]:
df1 = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
df2 = pd.DataFrame({"C":[1,2,3,4], "D":[5,6,7,8]})

merged_df = pd.concat([df1, df2], axis = 1, ignore_index = False)
merged_df

A  B  C  D
0  1  5  1  5
1  2  6  2  6
2  3  7  3  7
3  4  8  4  8

#### concat을 이용한 여러 csv 파일 합치기

In [44]:
df1 = pd.read_csv("일별 오염 데이터/2004-03-14_오염_수준.txt", sep = "\t", engine = "python")
df2 = pd.read_csv("일별 오염 데이터/2004-03-20_오염_수준.txt", sep = "\t", engine = "python")

In [45]:
df1.head() # 합쳐야 하는 데이터 구조

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0  2004-03-14  00:00:00     2.9      1533.50      93.0  10.963458   
1  2004-03-14  01:00:00     2.8      1483.50     131.0  11.860179   
2  2004-03-14  02:00:00     2.5      1366.75      92.0   8.624679   
3  2004-03-14  03:00:00     2.4      1344.00     132.0   9.737786   
4  2004-03-14  04:00:00  -200.0      1129.50      56.0   5.191654   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1013.00    190.0        888.50    129.0       1610.75      1534.75   
1        1044.75    174.0        879.75    119.0       1624.25      1529.75   
2         924.50    128.0        952.50    104.0       1543.00      1337.00   
3         967.75   -200.0        920.50   -200.0       1619.75      1278.25   
4         773.00     70.0       1130.25     82.0       1451.75      1050.50   

       T         RH        AH  
0  13.95  53.600000  0.849772  
1  14.65  51.500000  0.853623  
2  12.55  58.900001  0.853740  
3  11.65  63.425000  0.867449  
4  12.10  61.100001  0.860316

In [46]:
df2.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  2004-03-20  00:00:00     1.7      1126.75    -200.0  5.791192   
1  2004-03-20  01:00:00     1.6      1090.25    -200.0  5.191654   
2  2004-03-20  02:00:00     1.3      1017.00    -200.0  4.123187   
3  2004-03-20  03:00:00     1.3       997.25    -200.0  3.410629   
4  2004-03-20  04:00:00  -200.0       944.75    -200.0  2.908548   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         802.00    104.0       1064.00     92.0       1446.50       837.00   
1         773.00      NaN       1105.25     83.0       1428.50       761.00   
2         717.50     74.0       1181.75     81.0       1382.25       650.25   
3         677.00   -200.0       1252.25   -200.0       1358.50       590.75   
4         646.25     44.0       1308.00     55.0       1331.50       505.00   

        T     RH        AH  
0  13.775  57.95  0.908544  
1  13.900  55.95  0.884207  
2  13.875  55.55  0.876488  
3  13.825  55.10  0.866620  
4  13.800  54.60  0.857388

In [47]:
df2.shape

(24, 15)

In [48]:
df1.shape

(24, 15)

In [49]:
os.listdir('일별 오염 데이터')

['2004-03-11_오염_수준.txt',
 '2004-03-12_오염_수준.txt',
 '2004-03-13_오염_수준.txt',
 '2004-03-14_오염_수준.txt',
 '2004-03-15_오염_수준.txt',
 '2004-03-16_오염_수준.txt',
 '2004-03-17_오염_수준.txt',
 '2004-03-18_오염_수준.txt',
 '2004-03-19_오염_수준.txt',
 '2004-03-20_오염_수준.txt',
 '2004-03-21_오염_수준.txt',
 '2004-03-22_오염_수준.txt',
 '2004-03-23_오염_수준.txt',
 '2004-03-24_오염_수준.txt',
 '2004-03-25_오염_수준.txt',
 '2004-03-26_오염_수준.txt',
 '2004-03-27_오염_수준.txt',
 '2004-03-28_오염_수준.txt',
 '2004-03-29_오염_수준.txt',
 '2004-03-30_오염_수준.txt',
 '2004-03-31_오염_수준.txt',
 'desktop.ini']

In [53]:
merged_df = pd.DataFrame()
for file in os.listdir('일별 오염 데이터'):
    if '오염_수준.txt' in file:
        df = pd.read_csv('일별 오염 데이터/'+file, sep = '\t', engine = 'python')
        merged_df = pd.concat([merged_df,df], axis = 0, ignore_index = True)
        
merged_df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  2004-03-11  00:00:00     1.2      1185.00      31.0  3.624399   
1  2004-03-11  01:00:00     1.0      1136.25      31.0  3.326677   
2  2004-03-11  02:00:00     0.9      1094.00      24.0  2.339416   
3  2004-03-11  03:00:00     0.6      1009.75      19.0  1.696658   
4  2004-03-11  04:00:00  -200.0      1011.00      14.0  1.293620   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         689.50     62.0       1461.75     77.0       1332.75       732.50   
1         672.00     62.0       1453.25     76.0       1332.75       729.50   
2         608.50     45.0       1579.00     60.0       1276.00       619.50   
3         560.75   -200.0       1705.00   -200.0       1234.75       501.25   
4         526.75     21.0       1817.50     34.0       1196.75       445.25   

        T         RH        AH  
0  11.325  56.775000  0.760312  
1  10.675  60.000000  0.770238  
2  10.650  59.674999  0.764819  
3  10.250  60.200001  0.751657  
4  10.075  60.474999  0.746495

In [54]:
merged_df.shape

(504, 15)

#### concat을 이용한 엑셀 시트 통합

In [55]:
import xlrd
wb = xlrd.open_workbook('월별매출데이터.xlsx', on_demand = True)
sheetnames = wb.sheet_names()
sheetnames

['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']

In [59]:
df.shape

(1509, 8)

In [60]:
merged_df.shape

(18229, 8)