In [3]:
dic = {1:1, 2:4,3:6,4:9}

In [4]:
dic[2]

4

In [5]:
dic[4]

9

In [8]:
dic[5] = 20 #새로운 요소 추가

In [9]:
print(dic)

{1: 1, 2: 4, 3: 6, 4: 9, 5: 20}


In [10]:
dic.keys()

dict_keys([1, 2, 3, 4, 5])

In [11]:
dic.values()

dict_values([1, 4, 6, 9, 20])

In [12]:
dic.items()

dict_items([(1, 1), (2, 4), (3, 6), (4, 9), (5, 20)])

In [13]:
for key, val in dic.items():
    print(key,val)

1 1
2 4
3 6
4 9
5 20


In [14]:
for key in dic.keys():
    dic[key] = dic[key]*0.5

In [15]:
print(dic)

{1: 0.5, 2: 2.0, 3: 3.0, 4: 4.5, 5: 10.0}


In [17]:
L = [1,2,3,4,5]
for l in L:
    print(l)
    if l == 3:
        break

1
2
3


In [18]:
list(range(1,5,2))

[1, 3]

In [20]:
for i in range(2,10):
    for j in range(2,10):
        print('{}*{}={}'.format(i,j,i*j))

2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81


In [21]:
import itertools

In [22]:
for a,b,c in itertools.product(range(5),range(5),range(5)):
    print(a,b,c)

0 0 0
0 0 1
0 0 2
0 0 3
0 0 4
0 1 0
0 1 1
0 1 2
0 1 3
0 1 4
0 2 0
0 2 1
0 2 2
0 2 3
0 2 4
0 3 0
0 3 1
0 3 2
0 3 3
0 3 4
0 4 0
0 4 1
0 4 2
0 4 3
0 4 4
1 0 0
1 0 1
1 0 2
1 0 3
1 0 4
1 1 0
1 1 1
1 1 2
1 1 3
1 1 4
1 2 0
1 2 1
1 2 2
1 2 3
1 2 4
1 3 0
1 3 1
1 3 2
1 3 3
1 3 4
1 4 0
1 4 1
1 4 2
1 4 3
1 4 4
2 0 0
2 0 1
2 0 2
2 0 3
2 0 4
2 1 0
2 1 1
2 1 2
2 1 3
2 1 4
2 2 0
2 2 1
2 2 2
2 2 3
2 2 4
2 3 0
2 3 1
2 3 2
2 3 3
2 3 4
2 4 0
2 4 1
2 4 2
2 4 3
2 4 4
3 0 0
3 0 1
3 0 2
3 0 3
3 0 4
3 1 0
3 1 1
3 1 2
3 1 3
3 1 4
3 2 0
3 2 1
3 2 2
3 2 3
3 2 4
3 3 0
3 3 1
3 3 2
3 3 3
3 3 4
3 4 0
3 4 1
3 4 2
3 4 3
3 4 4
4 0 0
4 0 1
4 0 2
4 0 3
4 0 4
4 1 0
4 1 1
4 1 2
4 1 3
4 1 4
4 2 0
4 2 1
4 2 2
4 2 3
4 2 4
4 3 0
4 3 1
4 3 2
4 3 3
4 3 4
4 4 0
4 4 1
4 4 2
4 4 3
4 4 4


In [25]:
for a,b in itertools.product(range(2,10),range(2,10)):
    print('{}*{}={}'.format(a,b,a*b))


2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81


In [26]:
# zip
for a,b,c in zip(range(5),range(5),range(5)):
    print(a,b,c)

0 0 0
1 1 1
2 2 2
3 3 3
4 4 4


In [30]:
L =['a','b','c','d']
for comb in itertools.combinations(L,3):
    print(comb)

('a', 'b', 'c')
('a', 'b', 'd')
('a', 'c', 'd')
('b', 'c', 'd')


In [32]:
for r in range(1,len(L)+1):
    for p in itertools.permutations(L,r):
        print(p)

('a',)
('b',)
('c',)
('d',)
('a', 'b')
('a', 'c')
('a', 'd')
('b', 'a')
('b', 'c')
('b', 'd')
('c', 'a')
('c', 'b')
('c', 'd')
('d', 'a')
('d', 'b')
('d', 'c')
('a', 'b', 'c')
('a', 'b', 'd')
('a', 'c', 'b')
('a', 'c', 'd')
('a', 'd', 'b')
('a', 'd', 'c')
('b', 'a', 'c')
('b', 'a', 'd')
('b', 'c', 'a')
('b', 'c', 'd')
('b', 'd', 'a')
('b', 'd', 'c')
('c', 'a', 'b')
('c', 'a', 'd')
('c', 'b', 'a')
('c', 'b', 'd')
('c', 'd', 'a')
('c', 'd', 'b')
('d', 'a', 'b')
('d', 'a', 'c')
('d', 'b', 'a')
('d', 'b', 'c')
('d', 'c', 'a')
('d', 'c', 'b')
('a', 'b', 'c', 'd')
('a', 'b', 'd', 'c')
('a', 'c', 'b', 'd')
('a', 'c', 'd', 'b')
('a', 'd', 'b', 'c')
('a', 'd', 'c', 'b')
('b', 'a', 'c', 'd')
('b', 'a', 'd', 'c')
('b', 'c', 'a', 'd')
('b', 'c', 'd', 'a')
('b', 'd', 'a', 'c')
('b', 'd', 'c', 'a')
('c', 'a', 'b', 'd')
('c', 'a', 'd', 'b')
('c', 'b', 'a', 'd')
('c', 'b', 'd', 'a')
('c', 'd', 'a', 'b')
('c', 'd', 'b', 'a')
('d', 'a', 'b', 'c')
('d', 'a', 'c', 'b')
('d', 'b', 'a', 'c')
('d', 'b', 'c',

In [33]:
import numpy as np

In [35]:
a = np.array([1,4,2,5,3])
b = np.array([3.14, 4, 2, 3])
c = np.array([1,2,3,4,],dtype= float)
print(a,b,c)

[1 4 2 5 3] [3.14 4.   2.   3.  ] [1. 2. 3. 4.]


In [36]:
a = np.zeros((3,5), dtype = int)

In [37]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
b = np.ones((3,5), dtype = float)

In [39]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
c = np.full((3,5), 3.14) # 3.14로 채운 배열 만들기
c

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [41]:
d = np.arange(0,22,2) # 0에서 시작해 2씩 더해 20까지 채우는 배열 생성

In [43]:
d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
e = np.linspace(0,1,5) # 0,1사이의 일정한 간격으로 값 생성
e

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.random.random((3,5))

array([[0.8300319 , 0.40367706, 0.24310901, 0.21254564, 0.50334342],
       [0.63873444, 0.78010122, 0.58711474, 0.17044239, 0.46672172],
       [0.24004053, 0.01521652, 0.18376206, 0.73445246, 0.46671136]])

In [46]:
np.arange(3)

array([0, 1, 2])

In [47]:
np.arange(3).reshape(3,1)

array([[0],
       [1],
       [2]])