In [1]:
import numpy as np
from scipy.stats import *
import pandas as pd

In [2]:
#### 분산 계산
x = [1, 2, 3, 4, 5]
print(np.var(x, ddof = 1)) # 분모 = n - 1 ( 5 - 1)
print(np.array(x).var()) # 분모 = n
print(pd.Series(x).var(ddof = 0)) # 분모 = n

2.5
2.0
2.0


#### 표준편차 계산

In [3]:
x = [1, 2, 3, 4, 5]
print(np.std(x, ddof = 1))
print(np.array(x).std())
print(pd.Series(x).std(ddof = 1))

1.5811388300841898
1.4142135623730951
1.5811388300841898


#### 변동계수의 필요성

In [4]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = x1 * 10

print(np.std(x1, ddof = 1))
print(np.std(x2, ddof = 1))

1.5811388300841898
15.811388300841896


In [5]:
print(variation(x1)) # 변동 계수
print(variation(x2))

0.47140452079103173
0.4714045207910317


In [7]:
print(np.std(x1, ddof = 1) / np.mean(x1))
print(np.std(x2, ddof = 1) / np.mean(x2))

0.5270462766947299
0.5270462766947299


#### 스케일링

In [8]:
x1

array([1, 2, 3, 4, 5])

In [9]:
x2

array([10, 20, 30, 40, 50])

In [10]:
z1 = (x1 - x1.mean()) / x1.std()
z2 = (x2 - x2.mean()) / x2.std()

print(z1)
print(z2)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [11]:
# sklearn을 이용한 스케일링
X = pd.DataFrame({"X1":[1, 2, 3, 4, 5],
    "X2": [10, 20, 30, 40, 50]})

X

X1  X2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler() # 인스턴스화
Z = scaler.fit_transform(X) # fit_transform => ndarray
pd.DataFrame(Z)

0     1
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

#### 범위와 사분위 범위 계산 

In [13]:
x = np.random.normal(100, 20, size = 1000)
x

array([109.6572823 , 111.82819394, 106.08693307,  88.19027957,
       105.03663158,  98.62702923,  62.26572777, 123.57652272,
       120.24519445,  86.55188884, 118.88846319,  90.20316075,
        83.72363565, 111.33356816, 107.80770557, 111.07377046,
       127.2211773 ,  93.6946918 , 121.44330605,  92.43824045,
        84.55343799, 113.92920427, 110.25401654, 118.18829456,
       109.12721819,  97.35738505, 114.97728152, 101.80186191,
       110.80994636,  91.67344685, 102.63316053, 109.79692325,
        80.91771374, 105.66910289, 114.4367276 ,  88.68854539,
        78.20620886, 103.44070101, 111.14748923,  74.05745233,
        95.52193036, 115.84912603, 143.09449399, 114.77955688,
       120.11429119, 107.17233937,  87.2935581 , 108.59413625,
       133.15102273, 105.74595276,  89.87260328, 103.95583641,
       132.9173815 , 104.16381249,  62.96731742,  50.11375468,
        65.16921638,  85.70962741, 112.63141715,  81.09009105,
       122.42709061,  68.41029052, 104.36110867, 102.33

In [14]:
print(np.ptp(x))
print(np.max(x) - np.min(x))

115.91131208778704
115.91131208778704


In [15]:
print(np.quantile(x, 0.75) - np.quantile(x, 0.25))
print(iqr(x))

26.7760383115984
26.7760383115984
